import { AuthLogic } from './creator-logic.js?v=cache-bust-005';
import { initSelection } from './selection.js?v=cache-bust-005';
import { AuthUIManager } from './auth-ui.js?v=cache-bust-005';
import { CharacterCreatorUIManager } from './character-creator-ui.js?v=cache-bust-005';
import { InGameMenuUIManager } from './in-game-menu-ui.js?v=cache-bust-005';

const applyUIScaling = () => {
  const scalers = document.querySelectorAll('.screen-scaler');
  const scale = Math.min(window.innerWidth / 1920, window.innerHeight / 1080);
  scalers.forEach(scaler => {
    scaler.style.left = '0';
    scaler.style.top = '50%';
    scaler.style.transformOrigin = 'left center';
    scaler.style.transform = `translate(0, -50%) scale(${scale})`;
  });
};
window.addEventListener('resize', applyUIScaling);
applyUIScaling();

const modal = document.getElementById('custom-modal');
document.getElementById('modal-close').onclick = () => modal.style.display = 'none';

document.addEventListener('keydown', (e) => {
  if (e.key === 'Enter' && modal.style.display === 'flex') {
    e.preventDefault();
    document.getElementById('modal-close').click();
  }
});

class MenuAudioManager {
  constructor() {
    this.audio = new Audio('assets/audio/music/metallic-crackers.mp3');
    this.isMuted = localStorage.getItem('b_menu_muted') === 'true';
    this.audio.muted = this.isMuted;
    this.baseVolume = parseFloat(localStorage.getItem('b_menu_volume') || '0.3');
    this.audio.volume = this.baseVolume;
    this.isPlaying = false;
    this.fadeInterval = null;
    this.loopTimeout = null;

    this.audio.addEventListener('ended', () => {
      if (!this.isPlaying) return;
      this.loopTimeout = setTimeout(() => {
        if (this.isPlaying) this.audio.play().catch(e => {});
      }, 60000); // 1 minute pause between loops
    });

    const tryPlay = (e) => {
      if (e && !e.isTrusted) return; // Ignore programmatic clicks generated by the UI!
      if (!this.isPlaying && document.getElementById('game-screen')?.style.display !== 'block') {
        this.play();
      }
      document.removeEventListener('click', tryPlay);
      document.removeEventListener('keydown', tryPlay);
    };

    // Browsers prevent autoplay until the user interacts with the page!
    document.addEventListener('click', tryPlay);
    document.addEventListener('keydown', tryPlay);
  }

  setVolume(vol) {
    this.baseVolume = vol;
    this.audio.volume = vol;
    if (vol > 0 && this.isMuted) {
      this.isMuted = false;
      this.audio.muted = false;
      localStorage.setItem('b_menu_muted', false);
    } else if (vol === 0) {
      this.isMuted = true;
      this.audio.muted = true;
      localStorage.setItem('b_menu_muted', true);
    }
  }

  play() {
    if (this.fadeInterval) { clearInterval(this.fadeInterval); this.fadeInterval = null; }
    if (this.loopTimeout) { clearTimeout(this.loopTimeout); this.loopTimeout = null; }
    this.isPlaying = true;
    this.audio.volume = this.baseVolume;
    this.audio.play().catch(e => console.warn('Audio autoplay prevented'));
  }

  fadeOutAndStop() {
    this.isPlaying = false;
    if (this.loopTimeout) { clearTimeout(this.loopTimeout); this.loopTimeout = null; }

    if (this.fadeInterval) clearInterval(this.fadeInterval);
    this.fadeInterval = setInterval(() => {
      if (this.audio.volume > 0.05) {
        this.audio.volume = Math.max(0, this.audio.volume - 0.05);
      } else {
        this.audio.pause();
        this.audio.currentTime = 0;
        this.audio.volume = this.baseVolume;
        clearInterval(this.fadeInterval);
        this.fadeInterval = null;
      }
    }, 150);
  }
}

const app = {
  auth: new AuthLogic(),
  currentAccount: null,
  initSelection: initSelection,
  showModal: (title, body) => {
    document.getElementById('modal-title').innerText = title;
    document.getElementById('modal-body').innerText = body;
    modal.style.display = 'flex';
  },
  menuAudio: new MenuAudioManager()
};

window.app = app;

new AuthUIManager(app);
new CharacterCreatorUIManager(app);
new InGameMenuUIManager(app);
