export const GAME_TIPS = [
  "Hold {sprint} to sprint and cover ground faster.",
  "Use the scroll wheel to zoom the map in and out on the main screen, the minimap, or the full-screen map (M)!",
  "Type /editmode in chat to access the builder tools.",
  "Left-Click and drag in Edit Mode to rapidly draw multi-block walls and floors.",
  "Hold {buildDragSelect} while dragging in Edit Mode to expand your building selection vertically along the Z-Axis.",
  "Hold {buildDelete} while dragging in Edit Mode to mass delete large areas of blocks.",
  "Right-Click while in Edit Mode to rapidly rotate the shape you are placing.",
  "Click the Compass needle to snap your camera orientation.",
  "Paper airplanes are great for bonking your friends.",
  "Press 'N' to quickly toggle Player and Entity Nameplates and Health bars.",
  "Toggle abilities like Flashlight use Battery Charge, which can be restored with Solar Power during the day.",
  "Drag and drop abilities from your Powers panel (P) to organize your hotbar.",
  "Passive abilities (blue) and Active Toggles (green) are displayed below your Energy bar.",
  "You can merge the Battery Charge and Energy bars in the Settings menu under Powers & Combat.",
  "Taking too long to load? A 'Potato Mode' button will appear to help you load in faster!",
  "Press 'C' in Edit Mode to toggle Cutout transparency for windows and grates.",
  "Press 'M' in Edit Mode to toggle Mesh UV mapping for precise Blockbench textures.",
  "Did you know you can play fully networked arcade games like Bepis and Operius? Just interact with an Arcade Cabinet!",
  "Type /tpz <zoneName> to instantly warp to a different dimension or zone.",
  "Open your Settings to tweak your Render Distance and custom Action Binds."
];
